BEGIN;

CREATE TABLE IF NOT EXISTS items (

    id     INTEGER NOT NULL PRIMARY KEY,
    basket INTEGER NOT NULL DEFAULT 0,
    sku    TEXT NOT NULL,
    count  INTEGER NOT NULL DEFAULT 1

);

COMMIT;